.\" Manpage for ahctl.
.\" Contact jens.eliasson@thingwave.com to correct errors or typos.
.TH man 1 "31 Jan 2023" "0.3.1" "twanchor man page"
.SH NAME
ahctl \- command line tool to interact with a local cloud.
.SH SYNOPSIS
.B ahctl
[ --verbose]

Only the most important options are listed here.

.SH DESCRIPTION
achtl can be used to check the avialbility of Eclipse Arrowhead core systems, and to interact with the ServiceRegistry.

.SH OPTIONS
The ahctl application takes several options:
.TP
.B --version
Prints the version, and then exits.
.TP
.B --verbose
Enables more debug printouts

.SH SEE ALSO

.SH BUGS
No known bugs, perhaps.

